# Generated by Django 4.1.7 on 2023-03-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, unique=True)),
                ('Key_Events', models.CharField(max_length=1000, unique=True)),
                ('Personality', models.CharField(max_length=1000, unique=True)),
                ('Physical_Traits', models.CharField(max_length=1000, unique=True)),
                ('Notes', models.CharField(blank=True, max_length=1000, unique=True)),
            ],
        ),
    ]
