# Generated by Django 4.1.7 on 2023-03-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30, unique=True)),
                ('Plot_Points', models.CharField(max_length=1000, unique=True)),
                ('Characters_Involved', models.CharField(max_length=1000, unique=True)),
                ('Notes', models.CharField(blank=True, max_length=1000, unique=True)),
            ],
        ),
    ]
