# Generated by Django 4.1.7 on 2023-03-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, unique=True)),
                ('Genre', models.CharField(max_length=1000, unique=True)),
                ('Language', models.CharField(max_length=1000, unique=True)),
                ('Culture', models.CharField(max_length=1000, unique=True)),
                ('Environment', models.CharField(max_length=1000, unique=True)),
                ('Rules_Laws', models.CharField(max_length=1000, unique=True)),
                ('History', models.CharField(blank=True, max_length=1000, unique=True)),
            ],
        ),
    ]
